<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUI7XvtT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUI7XvtT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUI7XvtT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUI7XvtT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUI7XvtT\App_KernelDevDebugContainer([
    'container.build_hash' => 'UI7XvtT',
    'container.build_id' => 'cc7a5272',
    'container.build_time' => 1636012485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUI7XvtT');
