<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6pvYwJB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6pvYwJB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6pvYwJB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6pvYwJB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6pvYwJB\App_KernelDevDebugContainer([
    'container.build_hash' => '6pvYwJB',
    'container.build_id' => 'e254708f',
    'container.build_time' => 1638474576,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6pvYwJB');
