<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5JxkAp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5JxkAp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW5JxkAp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW5JxkAp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW5JxkAp\App_KernelDevDebugContainer([
    'container.build_hash' => 'W5JxkAp',
    'container.build_id' => 'efd3b4e6',
    'container.build_time' => 1637416410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5JxkAp');
